import HeroSection from '@/components/heroSection'
import Head from 'next/head'
import Events from './events'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        {/* <h1>
          Main / Index Page
        </h1> */}
        <Events />
        <HeroSection />
      </main>
    </>
  )
}
